version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing...
  build:
    commands:
      - echo Building artefact...
      - mkdir -p out
      - cp -r ./* out || true
artifacts:
  files:
    - appspec.yml
    - scripts/**
    - index.html
